[package]
name = "block-engine"
version = "0.1.1"
edition = "2024"

[dependencies]
be-gateway = { path = "../gateway" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = "0.3"
anyhow = "1.0"
